DROP TABLE IF EXISTS FINCA CASCADE;
CREATE TABLE FINCA(
	ID_FINCA VARCHAR(20) PRIMARY KEY,
	LOCALIDAD VARCHAR(20),
	SUPERFICIE INT,
	F_COMPRA DATE,
	F_FIN DATE,
	ALIAS VARCHAR(60)
);

DROP TABLE IF EXISTS TRACTOR CASCADE;
CREATE TABLE TRACTOR(
	MATRICULA VARCHAR(9) PRIMARY KEY,
	MODELO VARCHAR(20),
	POTENCIA INT,
	ALTURA INT,
	ANCHO INT,
	F_ITV DATE,
	ANIO INT,
	ID_FINCA VARCHAR(20) REFERENCES FINCA(ID_FINCA) ON DELETE CASCADE
);

DROP TABLE IF EXISTS CONDUCTOR CASCADE;
CREATE TABLE CONDUCTOR(
		DNI VARCHAR(9) PRIMARY KEY,
		NOMBRE VARCHAR(20),
		APELLIDOS VARCHAR(20),
		F_NAC DATE,
		F_CONT DATE,
		F_FIN DATE,
		TLF VARCHAR(9),
		SALARIO INT,
		PERMISOS VARCHAR(20)
);

DROP TABLE IF EXISTS CONDUCE CASCADE;
CREATE TABLE CONDUCE(
	DNI VARCHAR(20) REFERENCES CONDUCTOR(DNI) ON DELETE CASCADE,
	FECHA DATE,
	LUGAR VARCHAR(20),
	HORAS INT,
	MATRICULA VARCHAR(8) REFERENCES TRACTOR(MATRICULA) ON DELETE CASCADE,
	CONSTRAINT PK_CONDUCE PRIMARY KEY(DNI,MATRICULA)
);

DROP TABLE IF EXISTS ENCARGADO CASCADE;
CREATE TABLE ENCARGADO(
		DNI VARCHAR(9) PRIMARY KEY,
		NOMBRE VARCHAR(20),
		APELLIDOS VARCHAR(20),
		F_NAC DATE,
		F_CONT DATE,
		F_FIN DATE,
		TLF VARCHAR(9),
		SALARIO INT,
		VH_EMPRESA VARCHAR(8)
);

DROP TABLE IF EXISTS TRABAJADOR CASCADE;
CREATE TABLE TRABAJADOR(
		DNI VARCHAR(9) PRIMARY KEY,
		NOMBRE VARCHAR(20),
		APELLIDOS VARCHAR(20),
		F_NAC DATE,
		F_CONT DATE,
		F_FIN DATE,
		TLF VARCHAR(9),
		SALARIO INT
);

DROP TABLE IF EXISTS DIRIGE CASCADE;
CREATE TABLE DIRIGE(
	DNI VARCHAR(9) REFERENCES ENCARGADO(DNI) ON DELETE CASCADE,
	F_INICIO DATE,
	F_FIN DATE,
	ID_FINCA VARCHAR(20) REFERENCES FINCA(ID_FINCA) ON DELETE CASCADE,
	CONSTRAINT PK_DIRIGE PRIMARY KEY(DNI,ID_FINCA)
);

DROP TABLE IF EXISTS FORMA CASCADE;
CREATE TABLE FORMA(
	DNI VARCHAR(9) REFERENCES TRABAJADOR(DNI) ON DELETE CASCADE,
	F_INICIO DATE,
	F_FIN DATE,
	ID_CUADRILLA VARCHAR(20) REFERENCES CUADRILLA(ID_CUADRILLA) ON DELETE CASCADE,
	CONSTRAINT PK_FORMA PRIMARY KEY(DNI,ID_CUADRILLA,F_INICIO)
);

DROP TABLE IF EXISTS LIDERA CASCADE;
CREATE TABLE LIDERA(
	DNI VARCHAR(9) REFERENCES ENCARGADO(DNI) ON DELETE CASCADE,
	F_INICIO DATE,
	F_FIN DATE,
	ID_CUADRILLA VARCHAR(20) ,
	CONSTRAINT PK_LIDERA PRIMARY KEY(DNI,ID_CUADRILLA)
);

DROP TABLE IF EXISTS CUADRILLA CASCADE;
CREATE TABLE CUADRILLA(
	ID_CUADRILLA VARCHAR(20) PRIMARY KEY,
	F_CREACION DATE,
	F_FIN DATE
);

DROP TABLE IF EXISTS TRABAJA CASCADE;
CREATE TABLE TRABAJA(
	ID_CUADRILLA VARCHAR(20) REFERENCES CUADRILLA(ID_CUADRILLA) ON DELETE CASCADE,
	FECHA DATE,
	HORAS INTEGER,
	TAREA VARCHAR(20),
	ID_EXPLOTACION VARCHAR(20) ,
	CONSTRAINT PK_TRABAJA PRIMARY KEY(ID_CUADRILLA,FECHA,TAREA,ID_EXPLOTACION)
);

DROP TABLE IF EXISTS EXPLOTACION CASCADE;
CREATE TABLE EXPLOTACION(
	ID_EXPLOTACION VARCHAR(20) PRIMARY KEY,
	SUPERFICIE INT,
	TIPO VARCHAR(25),
	F_CREACION DATE,
	F_FIN DATE,
	ALIAS VARCHAR(60),
	ID_FINCA VARCHAR(20) REFERENCES FINCA(ID_FINCA) ON DELETE CASCADE
);

DROP TABLE IF EXISTS PLANTACION CASCADE;
CREATE TABLE PLANTACION(
	ID_PLANT VARCHAR(20) PRIMARY KEY,
	TIPO VARCHAR(25),
	VARIEDAD VARCHAR(20),
	F_INICIO DATE,
	F_FIN DATE,
	ID_EXPLOTACION VARCHAR(20) REFERENCES EXPLOTACION(ID_EXPLOTACION) ON DELETE CASCADE
);

DROP TABLE IF EXISTS VENTA CASCADE;
CREATE TABLE VENTA(
	ID_VENTA VARCHAR(40),
	KG INT NOT NULL,
	PRECIO DECIMAL(4,2),
	TAMANIO VARCHAR(20),
	COLOR VARCHAR(20), 
	FECHA DATE,
	ID_PLANT VARCHAR(20) REFERENCES PLANTACION(ID_PLANT) ON DELETE CASCADE,
	CONSTRAINT PK_VENTA PRIMARY KEY(ID_VENTA,ID_PLANT)
);

DROP TABLE IF EXISTS GASTO CASCADE;
CREATE TABLE GASTO(
	ID_GASTO VARCHAR(40),
	CONCEPTO VARCHAR(40),
	DETALLES VARCHAR(300),
	IMPORTE DECIMAL(12,2),
	FECHA DATE,
	ID_FINCA VARCHAR(20) REFERENCES FINCA(ID_FINCA) ON DELETE CASCADE,
	CONSTRAINT PK_GASTO PRIMARY KEY(ID_GASTO,ID_FINCA)
);


CREATE OR REPLACE VIEW INGRESOS_VENTAS AS
SELECT ID_PLANT,(KG*PRECIO) AS INGRESOS, FECHA
FROM VENTA
