CREATE TABLE IF NOT EXISTS FINCA(
	ID_FINCA TEXT PRIMARY KEY,
	LOCALIDAD TEXT,
	SUPERFICIE INTEGEREGER,
	F_COMPRA TEXT,
	F_FIN TEXT,
	ALAIS TEXT
);

CREATE TABLE TRACTOR(
	MATRICULA TEXT(9) PRIMARY KEY,
	MODELO TEXT,
	POTENCIA INTEGER,
	ALTURA INTEGER,
	ANCHO INTEGER,
	F_ITV TEXT,
	ANIO INTEGER,
	ID_FINCA TEXT REFERENCES FINCA(ID_FINCA) ON DELETE CASCADE
);

CREATE TABLE CONDUCTOR(
		DNI TEXT(9) PRIMARY KEY,
		NOMBRE TEXT,
		APELLIDOS TEXT,
		F_NAC TEXT,
		F_CONT TEXT,
		F_FIN TEXT,
		TLF TEXT(9),
		SALARIO INTEGER,
		PERMISOS TEXT
);

CREATE TABLE CONDUCE(
	DNI TEXT REFERENCES CONDUCTOR(DNI) ON DELETE CASCADE,
	FECHA TEXT,
	LUGAR TEXT,
	HORAS INTEGER,
	MATRICULA TEXT(8) REFERENCES TRACTOR(MATRICULA) ON DELETE CASCADE,
	CONSTRAINTEGER PK_CONDUCE PRIMARY KEY(DNI,MATRICULA)
);

CREATE TABLE ENCARGADO(
		DNI TEXT(9) PRIMARY KEY,
		NOMBRE TEXT,
		APELLIDOS TEXT,
		F_NAC TEXT,
		F_CONT TEXT,
		F_FIN TEXT,
		TLF TEXT(9),
		SALARIO INTEGER,
		VH_EMPRESA TEXT(8)
);

CREATE TABLE TRABAJADOR(
		DNI TEXT(9) PRIMARY KEY,
		NOMBRE TEXT,
		APELLIDOS TEXT,
		F_NAC TEXT,
		F_CONT TEXT,
		F_FIN TEXT,
		TLF TEXT(9),
		SALARIO INTEGER
);

CREATE TABLE DIRIGE(
	DNI TEXT(9) REFERENCES ENCARGADO(DNI) ON DELETE CASCADE,
	F_INICIO TEXT,
	F_FIN TEXT,
	ID_FINCA TEXT REFERENCES FINCA(ID_FINCA) ON DELETE CASCADE,
	CONSTRAINTEGER PK_DIRIGE PRIMARY KEY(DNI,ID_FINCA)
);

CREATE TABLE FORMA(
	DNI TEXT(9) REFERENCES TRABAJADOR(DNI) ON DELETE CASCADE,
	F_INICIO TEXT,
	F_FIN TEXT,
	ID_CUADRILLA TEXT REFERENCES CUADRILLA(ID_CUADRILLA) ON DELETE CASCADE,
	CONSTRAINTEGER PK_FORMA PRIMARY KEY(DNI,ID_CUADRILLA,F_INICIO)
);

CREATE TABLE LIDERA(
	DNI TEXT(9) REFERENCES ENCARGADO(DNI) ON DELETE CASCADE,
	F_INICIO TEXT,
	F_FIN TEXT,
	ID_CUADRILLA TEXT ,
	CONSTRAINTEGER PK_LIDERA PRIMARY KEY(DNI,ID_CUADRILLA)
);

CREATE TABLE CUADRILLA(
	ID_CUADRILLA TEXT PRIMARY KEY,
	F_CREACION TEXT,
	F_FIN TEXT
);

CREATE TABLE TRABAJA(
	ID_CUADRILLA TEXT REFERENCES CUADRILLA(ID_CUADRILLA) ON DELETE CASCADE,
	FECHA TEXT,
	HORAS INTEGEREGER,
	TAREA TEXT,
	ID_EXPLOTACION TEXT ,
	CONSTRAINTEGER PK_TRABAJA PRIMARY KEY(ID_CUADRILLA,FECHA,TAREA,ID_EXPLOTACION)
);

CREATE TABLE EXPLOTACION(
	ID_EXPLOTACION TEXT PRIMARY KEY,
	SUPERFICIE INTEGER,
	TIPO TEXT,
	F_CREACION TEXT,
	F_FIN TEXT,
	ID_FINCA TEXT REFERENCES FINCA(ID_FINCA) ON DELETE CASCADE,
	ALIAS TEXT
);

CREATE TABLE PLANTACION(
	ID_PLANT TEXT PRIMARY KEY,
	TIPO TEXT,
	VARIEDAD TEXT,
	F_INICIO TEXT,
	F_FIN TEXT,
	ID_EXPLOTACION TEXT REFERENCES EXPLOTACION(ID_EXPLOTACION) ON DELETE CASCADE
);

CREATE TABLE VENTA(
	ID_VENTA TEXT,
	KG INTEGER NOT NULL,
	PRECIO DECIMAL(4,2),
	TAMANIO TEXT,
	COLOR TEXT, 
	FECHA TEXT,
	ID_PLANT TEXT REFERENCES PLANTACION(ID_PLANT) ON DELETE CASCADE,
	CONSTRAINTEGER PK_VENTA PRIMARY KEY(ID_VENTA,ID_PLANT)
);

CREATE TABLE GASTO(
	ID_GASTO TEXT,
	CONCEPTO TEXT,
	DETALLES TEXT(0),
	IMPORTE DECIMAL(,2),
	FECHA TEXT,
	ID_FINCA TEXT REFERENCES FINCA(ID_FINCA) ON DELETE CASCADE,
	CONSTRAINTEGER PK_GASTO PRIMARY KEY(ID_GASTO,ID_FINCA)
);
