/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1daw.vistas;

import java.awt.Toolkit;

/**
 *
 * @author Jaime-torre
 */
public class JFEmpleAdd extends javax.swing.JFrame {

    /**
     * Creates new form SelectFincaAdd
     */
    public JFEmpleAdd() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/proyecto1daw/img/icono_logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoEncargado = new javax.swing.ButtonGroup();
        jPanelBot = new javax.swing.JPanel();
        jPanelLista = new javax.swing.JPanel();
        jRadioEncargado = new javax.swing.JRadioButton();
        jRadioTractorista = new javax.swing.JRadioButton();
        jRadioEmpleado = new javax.swing.JRadioButton();
        campoNombre = new javax.swing.JTextField();
        campoDni = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        botonLimpiar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        campoFNac = new javax.swing.JTextField();
        jLabelFNac = new javax.swing.JLabel();
        campoTlf = new javax.swing.JTextField();
        jLabelTlf = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();
        jLabelSalario = new javax.swing.JLabel();
        campoFCont = new javax.swing.JTextField();
        jLabelFechaCont = new javax.swing.JLabel();
        campoFFinCont = new javax.swing.JTextField();
        campoPermisos = new javax.swing.JTextField();
        jLabelPermisos = new javax.swing.JLabel();
        campoVHEmpresa = new javax.swing.JTextField();
        jLabelVHEmpresa = new javax.swing.JLabel();
        errNombre = new javax.swing.JLabel();
        errApellidos = new javax.swing.JLabel();
        errDni = new javax.swing.JLabel();
        errFNac = new javax.swing.JLabel();
        errTlf = new javax.swing.JLabel();
        errSalario = new javax.swing.JLabel();
        errFCont = new javax.swing.JLabel();
        errFFin = new javax.swing.JLabel();
        errPermisos = new javax.swing.JLabel();
        errVhEmpresa = new javax.swing.JLabel();
        jCheckBoxFFin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir empleado");
        setBackground(new java.awt.Color(119, 182, 134));

        jPanelBot.setBackground(new java.awt.Color(176, 210, 184));

        jPanelLista.setBackground(new java.awt.Color(119, 182, 134));

        jRadioEncargado.setBackground(new java.awt.Color(119, 182, 134));
        buttonGroupTipoEncargado.add(jRadioEncargado);
        jRadioEncargado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioEncargado.setText("Encargado");
        jRadioEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEncargadoActionPerformed(evt);
            }
        });

        jRadioTractorista.setBackground(new java.awt.Color(119, 182, 134));
        buttonGroupTipoEncargado.add(jRadioTractorista);
        jRadioTractorista.setForeground(new java.awt.Color(255, 255, 255));
        jRadioTractorista.setText("Conductor");

        jRadioEmpleado.setBackground(new java.awt.Color(119, 182, 134));
        buttonGroupTipoEncargado.add(jRadioEmpleado);
        jRadioEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioEmpleado.setSelected(true);
        jRadioEmpleado.setText("Trabajador");

        javax.swing.GroupLayout jPanelListaLayout = new javax.swing.GroupLayout(jPanelLista);
        jPanelLista.setLayout(jPanelListaLayout);
        jPanelListaLayout.setHorizontalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jRadioEmpleado)
                .addGap(53, 53, 53)
                .addComponent(jRadioTractorista)
                .addGap(54, 54, 54)
                .addComponent(jRadioEncargado)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelListaLayout.setVerticalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioEmpleado)
                    .addComponent(jRadioTractorista)
                    .addComponent(jRadioEncargado))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        campoApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidosActionPerformed(evt);
            }
        });

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre");

        jLabelApellidos.setText("Apellidos");

        jLabelDni.setText("DNI");

        jLabelFNac.setText("Fecha nacimiento");

        jLabelTlf.setText("Teléfono");

        jLabelSalario.setText("Salario");

        jLabelFechaCont.setText("Fecha contratación");

        campoFFinCont.setEnabled(false);

        campoPermisos.setEnabled(false);

        jLabelPermisos.setText("Permisos");
        jLabelPermisos.setEnabled(false);

        campoVHEmpresa.setEnabled(false);

        jLabelVHEmpresa.setText("Matrícula VH empresa");
        jLabelVHEmpresa.setEnabled(false);

        errNombre.setForeground(java.awt.Color.red);
        errNombre.setText(" ");

        errApellidos.setForeground(java.awt.Color.red);
        errApellidos.setText(" ");

        errDni.setForeground(java.awt.Color.red);
        errDni.setText(" ");

        errFNac.setForeground(java.awt.Color.red);
        errFNac.setText(" ");

        errTlf.setForeground(java.awt.Color.red);
        errTlf.setText(" ");

        errSalario.setForeground(java.awt.Color.red);
        errSalario.setText(" ");

        errFCont.setForeground(java.awt.Color.red);
        errFCont.setText(" ");

        errFFin.setForeground(java.awt.Color.red);
        errFFin.setText(" ");

        errPermisos.setForeground(java.awt.Color.red);
        errPermisos.setText(" ");

        errVhEmpresa.setForeground(java.awt.Color.red);
        errVhEmpresa.setText(" ");

        jCheckBoxFFin.setBackground(new java.awt.Color(176, 210, 184));
        jCheckBoxFFin.setText("Fecha fin de contrato");

        javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
        jPanelBot.setLayout(jPanelBotLayout);
        jPanelBotLayout.setHorizontalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFCont, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaCont)
                            .addComponent(errFCont, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxFFin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errFFin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(campoFFinCont)
                                .addGap(13, 13, 13)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(jLabelDni)
                                .addGap(198, 198, 198))
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(campoDni)
                                .addGap(66, 66, 66)))
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(jLabelFNac)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campoFNac))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotLayout.createSequentialGroup()
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelTlf)
                                    .addComponent(campoTlf, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(errDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(errTlf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22)))
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSalario)
                            .addComponent(errFNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoSalario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(botonAceptar)
                                .addGap(63, 63, 63)
                                .addComponent(botonLimpiar)
                                .addGap(45, 45, 45)
                                .addComponent(botonCancelar))
                            .addComponent(jLabelPermisos)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelNombre)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(errNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66)
                                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(errApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelApellidos)
                                    .addComponent(campoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(errPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(errVhEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBotLayout.createSequentialGroup()
                                .addComponent(campoPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelVHEmpresa)
                                    .addComponent(campoVHEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanelBotLayout.setVerticalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errNombre)
                    .addComponent(errApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDni)
                    .addComponent(jLabelFNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errFNac)
                    .addComponent(errDni, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTlf)
                    .addComponent(jLabelSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFFin)
                    .addComponent(jLabelFechaCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFFinCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errFCont)
                    .addComponent(errFFin))
                .addGap(1, 1, 1)
                .addComponent(jPanelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVHEmpresa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPermisos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoVHEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errPermisos)
                    .addComponent(errVhEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiar)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void campoApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidosActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void jRadioEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioEncargadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmpleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmpleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmpleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmpleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmpleAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAceptar;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonLimpiar;
    private javax.swing.ButtonGroup buttonGroupTipoEncargado;
    public javax.swing.JTextField campoApellidos;
    public javax.swing.JTextField campoDni;
    public javax.swing.JTextField campoFCont;
    public javax.swing.JTextField campoFFinCont;
    public javax.swing.JTextField campoFNac;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JTextField campoPermisos;
    public javax.swing.JTextField campoSalario;
    public javax.swing.JTextField campoTlf;
    public javax.swing.JTextField campoVHEmpresa;
    public javax.swing.JLabel errApellidos;
    public javax.swing.JLabel errDni;
    public javax.swing.JLabel errFCont;
    public javax.swing.JLabel errFFin;
    public javax.swing.JLabel errFNac;
    public javax.swing.JLabel errNombre;
    public javax.swing.JLabel errPermisos;
    public javax.swing.JLabel errSalario;
    public javax.swing.JLabel errTlf;
    public javax.swing.JLabel errVhEmpresa;
    public javax.swing.JCheckBox jCheckBoxFFin;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelFNac;
    private javax.swing.JLabel jLabelFechaCont;
    private javax.swing.JLabel jLabelNombre;
    public javax.swing.JLabel jLabelPermisos;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTlf;
    public javax.swing.JLabel jLabelVHEmpresa;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelLista;
    public javax.swing.JRadioButton jRadioEmpleado;
    public javax.swing.JRadioButton jRadioEncargado;
    public javax.swing.JRadioButton jRadioTractorista;
    // End of variables declaration//GEN-END:variables
}
