/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1daw.vistas;

/**
 *
 * @author Jaime-torre
 */
public class JFEmpleAdd extends javax.swing.JFrame {

    /**
     * Creates new form SelectFincaAdd
     */
    public JFEmpleAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoEncargado = new javax.swing.ButtonGroup();
        jPanelBot = new javax.swing.JPanel();
        jPanelLista = new javax.swing.JPanel();
        jRadioEncargado = new javax.swing.JRadioButton();
        jRadioTractorista = new javax.swing.JRadioButton();
        jRadioEmpleado = new javax.swing.JRadioButton();
        campoNombre = new javax.swing.JTextField();
        campoDni = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        botonReset = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonAceptar1 = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        campoFNac = new javax.swing.JTextField();
        jLabelFNac = new javax.swing.JLabel();
        campoTlf = new javax.swing.JTextField();
        jLabelTlf = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();
        jLabelSalario = new javax.swing.JLabel();
        campoFCont = new javax.swing.JTextField();
        jLabelFechaCont = new javax.swing.JLabel();
        campoFFinCont = new javax.swing.JTextField();
        jLabelFCont = new javax.swing.JLabel();
        campoDni6 = new javax.swing.JTextField();
        jLabelPermisos = new javax.swing.JLabel();
        campoDni7 = new javax.swing.JTextField();
        jLabelVHEmpresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir empleado");
        setBackground(new java.awt.Color(119, 182, 134));

        jPanelBot.setBackground(new java.awt.Color(119, 182, 134));

        jPanelLista.setBackground(new java.awt.Color(176, 210, 184));

        jRadioEncargado.setBackground(new java.awt.Color(176, 210, 184));
        buttonGroupTipoEncargado.add(jRadioEncargado);
        jRadioEncargado.setText("Encargado");
        jRadioEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEncargadoActionPerformed(evt);
            }
        });

        jRadioTractorista.setBackground(new java.awt.Color(176, 210, 184));
        buttonGroupTipoEncargado.add(jRadioTractorista);
        jRadioTractorista.setText("Conductor");

        jRadioEmpleado.setBackground(new java.awt.Color(176, 210, 184));
        buttonGroupTipoEncargado.add(jRadioEmpleado);
        jRadioEmpleado.setText("Trabajador");

        javax.swing.GroupLayout jPanelListaLayout = new javax.swing.GroupLayout(jPanelLista);
        jPanelLista.setLayout(jPanelListaLayout);
        jPanelListaLayout.setHorizontalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jRadioEmpleado)
                .addGap(26, 26, 26)
                .addComponent(jRadioTractorista)
                .addGap(39, 39, 39)
                .addComponent(jRadioEncargado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelListaLayout.setVerticalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioEmpleado)
                    .addComponent(jRadioTractorista)
                    .addComponent(jRadioEncargado))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        campoApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidosActionPerformed(evt);
            }
        });

        botonReset.setBackground(new java.awt.Color(119, 182, 134));
        botonReset.setText("Limpiar");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(119, 182, 134));
        botonCancelar.setText("Cancelar");

        botonAceptar1.setBackground(new java.awt.Color(119, 182, 134));
        botonAceptar1.setText("Aceptar");
        botonAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptar1ActionPerformed(evt);
            }
        });

        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");

        jLabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidos.setText("Apellidos");

        jLabelDni.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDni.setText("DNI");

        jLabelFNac.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFNac.setText("Fecha nacimiento");

        jLabelTlf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTlf.setText("Teléfono");

        jLabelSalario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalario.setText("Salario");

        jLabelFechaCont.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaCont.setText("Fecha contratación");

        jLabelFCont.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFCont.setText("Fecha fin contrato");

        campoDni6.setEnabled(false);

        jLabelPermisos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPermisos.setText("Permisos");
        jLabelPermisos.setEnabled(false);

        campoDni7.setEnabled(false);

        jLabelVHEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVHEmpresa.setText("Matrícula VH empresa");
        jLabelVHEmpresa.setEnabled(false);

        javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
        jPanelBot.setLayout(jPanelBotLayout);
        jPanelBotLayout.setHorizontalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(botonAceptar1)
                        .addGap(24, 24, 24)
                        .addComponent(botonReset)
                        .addGap(24, 24, 24)
                        .addComponent(botonCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(jLabelFNac)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campoFNac)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelApellidos)
                                .addGap(118, 118, 118))
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(campoApellidos)))))
                .addContainerGap())
            .addComponent(jPanelLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(128, 302, Short.MAX_VALUE))
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addComponent(campoTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(jLabelSalario)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(campoSalario)
                                .addContainerGap())))
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(campoFCont, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelBotLayout.createSequentialGroup()
                                        .addComponent(jLabelFCont)
                                        .addGap(74, 74, 74))
                                    .addComponent(campoFFinCont)))
                            .addComponent(jLabelDni)
                            .addComponent(jLabelTlf)
                            .addComponent(jLabelFechaCont))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBotLayout.createSequentialGroup()
                                .addComponent(campoDni6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelVHEmpresa)
                                    .addComponent(campoDni7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelPermisos))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        jPanelBotLayout.setVerticalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDni)
                    .addComponent(jLabelFNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTlf)
                    .addComponent(jLabelSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaCont)
                    .addComponent(jLabelFCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFFinCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPermisos)
                    .addComponent(jLabelVHEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDni6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDni7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonReset)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar1))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonResetActionPerformed

    private void campoApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidosActionPerformed

    private void botonAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAceptar1ActionPerformed

    private void jRadioEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioEncargadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmpleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmpleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmpleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmpleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmpleAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAceptar1;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonReset;
    private javax.swing.ButtonGroup buttonGroupTipoEncargado;
    public javax.swing.JTextField campoApellidos;
    public javax.swing.JTextField campoDni;
    public javax.swing.JTextField campoDni6;
    public javax.swing.JTextField campoDni7;
    public javax.swing.JTextField campoFCont;
    public javax.swing.JTextField campoFFinCont;
    public javax.swing.JTextField campoFNac;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JTextField campoSalario;
    public javax.swing.JTextField campoTlf;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelFCont;
    private javax.swing.JLabel jLabelFNac;
    private javax.swing.JLabel jLabelFechaCont;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPermisos;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTlf;
    private javax.swing.JLabel jLabelVHEmpresa;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelLista;
    private javax.swing.JRadioButton jRadioEmpleado;
    private javax.swing.JRadioButton jRadioEncargado;
    private javax.swing.JRadioButton jRadioTractorista;
    // End of variables declaration//GEN-END:variables
}
