/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1daw.vistas;

/**
 *
 * @author Jaime-torre
 */
public class JFEmpleadosOld extends javax.swing.JPanel {

    /**
     * Creates new form TrabajadoresCuadrillas
     */
    public JFEmpleadosOld() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCuadrillas = new javax.swing.JPanel();
        jPanelTop1 = new javax.swing.JPanel();
        listaFincas1 = new javax.swing.JLabel();
        jLabelGestionar2 = new javax.swing.JLabel();
        jPanelBot1 = new javax.swing.JPanel();
        jLabelGestionar3 = new javax.swing.JLabel();
        jLabelAdd1 = new javax.swing.JLabel();
        jLabelMod1 = new javax.swing.JLabel();
        jLabelInfo1 = new javax.swing.JLabel();
        jLabelEliminar1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelTrabajos = new javax.swing.JPanel();
        jPanelTop2 = new javax.swing.JPanel();
        listaFincas2 = new javax.swing.JLabel();
        jLabelGestionar4 = new javax.swing.JLabel();
        jPanelBot2 = new javax.swing.JPanel();
        jLabelAdd2 = new javax.swing.JLabel();
        jLabelMod2 = new javax.swing.JLabel();
        jLabelEliminar2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanelTrabajadores = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        listaFincas = new javax.swing.JLabel();
        jLabelGestionar1 = new javax.swing.JLabel();
        jCheckBoxTract = new javax.swing.JCheckBox();
        jCheckBoxEmp1 = new javax.swing.JCheckBox();
        jCheckBoxEnc = new javax.swing.JCheckBox();
        jCheckBoxFin = new javax.swing.JCheckBox();
        jPanelBot = new javax.swing.JPanel();
        jLabelCambiar = new javax.swing.JLabel();
        jLabelAdd = new javax.swing.JLabel();
        jLabelMod = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelCuadrillas1 = new javax.swing.JPanel();
        jPanelTop3 = new javax.swing.JPanel();
        listaFincas3 = new javax.swing.JLabel();
        jLabelGestionar5 = new javax.swing.JLabel();
        jPanelBot3 = new javax.swing.JPanel();
        jLabelGestionar6 = new javax.swing.JLabel();
        jLabelAdd3 = new javax.swing.JLabel();
        jLabelMod3 = new javax.swing.JLabel();
        jLabelInfo2 = new javax.swing.JLabel();
        jLabelEliminar3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanelTrabajos1 = new javax.swing.JPanel();
        jPanelTop4 = new javax.swing.JPanel();
        listaFincas4 = new javax.swing.JLabel();
        jLabelGestionar7 = new javax.swing.JLabel();
        jPanelBot4 = new javax.swing.JPanel();
        jLabelAdd4 = new javax.swing.JLabel();
        jLabelMod4 = new javax.swing.JLabel();
        jLabelEliminar4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanelTrabajadores1 = new javax.swing.JPanel();
        jPanelTop5 = new javax.swing.JPanel();
        listaFincas5 = new javax.swing.JLabel();
        jLabelGestionar8 = new javax.swing.JLabel();
        jCheckBoxTract1 = new javax.swing.JCheckBox();
        jCheckBoxEmp2 = new javax.swing.JCheckBox();
        jCheckBoxEnc1 = new javax.swing.JCheckBox();
        jCheckBoxFin1 = new javax.swing.JCheckBox();
        jPanelBot5 = new javax.swing.JPanel();
        jLabelCambiar1 = new javax.swing.JLabel();
        jLabelAdd5 = new javax.swing.JLabel();
        jLabelMod5 = new javax.swing.JLabel();
        jLabelInfo3 = new javax.swing.JLabel();
        jLabelEliminar5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();

        jPanelTop1.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop1.setToolTipText("");
        jPanelTop1.setPreferredSize(new java.awt.Dimension(954, 100));

        listaFincas1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas1.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas1.setText("Cuadrillas");

        jLabelGestionar2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar2.setText("Volver");

        javax.swing.GroupLayout jPanelTop1Layout = new javax.swing.GroupLayout(jPanelTop1);
        jPanelTop1.setLayout(jPanelTop1Layout);
        jPanelTop1Layout.setHorizontalGroup(
            jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar2)
                .addGap(184, 184, 184)
                .addComponent(listaFincas1)
                .addContainerGap(486, Short.MAX_VALUE))
        );
        jPanelTop1Layout.setVerticalGroup(
            jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelBot1.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot1.setToolTipText("");

        jLabelGestionar3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_gest.png"))); // NOI18N
        jLabelGestionar3.setText("Nuevo trabajo");

        jLabelAdd1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd1.setText("Añadir");

        jLabelMod1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod1.setText("Modificar");

        jLabelInfo1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelInfo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_info.png"))); // NOI18N
        jLabelInfo1.setText("Informacion");

        jLabelEliminar1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar1.setText("Eliminar");

        javax.swing.GroupLayout jPanelBot1Layout = new javax.swing.GroupLayout(jPanelBot1);
        jPanelBot1.setLayout(jPanelBot1Layout);
        jPanelBot1Layout.setHorizontalGroup(
            jPanelBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabelGestionar3)
                .addGap(64, 64, 64)
                .addComponent(jLabelAdd1)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod1)
                .addGap(64, 64, 64)
                .addComponent(jLabelInfo1)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBot1Layout.setVerticalGroup(
            jPanelBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGestionar3)
                    .addComponent(jLabelAdd1)
                    .addComponent(jLabelMod1)
                    .addComponent(jLabelInfo1)
                    .addComponent(jLabelEliminar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Encargado", "último trab.", "F. Creación"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelCuadrillasLayout = new javax.swing.GroupLayout(jPanelCuadrillas);
        jPanelCuadrillas.setLayout(jPanelCuadrillasLayout);
        jPanelCuadrillasLayout.setHorizontalGroup(
            jPanelCuadrillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop1, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
            .addComponent(jPanelBot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanelCuadrillasLayout.setVerticalGroup(
            jPanelCuadrillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCuadrillasLayout.createSequentialGroup()
                .addComponent(jPanelTop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jTabbedPane1.addTab("Cuadrillas", jPanelCuadrillas);

        jPanelTop2.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop2.setToolTipText("");
        jPanelTop2.setPreferredSize(new java.awt.Dimension(954, 100));

        listaFincas2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas2.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas2.setText("Trabajos");

        jLabelGestionar4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar4.setText("Volver");

        javax.swing.GroupLayout jPanelTop2Layout = new javax.swing.GroupLayout(jPanelTop2);
        jPanelTop2.setLayout(jPanelTop2Layout);
        jPanelTop2Layout.setHorizontalGroup(
            jPanelTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar4)
                .addGap(235, 235, 235)
                .addComponent(listaFincas2)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanelTop2Layout.setVerticalGroup(
            jPanelTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelBot2.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot2.setToolTipText("");

        jLabelAdd2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd2.setText("Añadir");

        jLabelMod2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod2.setText("Modificar");

        jLabelEliminar2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar2.setText("Eliminar");

        javax.swing.GroupLayout jPanelBot2Layout = new javax.swing.GroupLayout(jPanelBot2);
        jPanelBot2.setLayout(jPanelBot2Layout);
        jPanelBot2Layout.setHorizontalGroup(
            jPanelBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot2Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabelAdd2)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod2)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar2)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanelBot2Layout.setVerticalGroup(
            jPanelBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdd2)
                    .addComponent(jLabelMod2)
                    .addComponent(jLabelEliminar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cuadrilla", "Fecha", "Horas", "Tipo", "Explotacion", "Encargado"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanelTrabajosLayout = new javax.swing.GroupLayout(jPanelTrabajos);
        jPanelTrabajos.setLayout(jPanelTrabajosLayout);
        jPanelTrabajosLayout.setHorizontalGroup(
            jPanelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop2, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
            .addComponent(jPanelBot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanelTrabajosLayout.setVerticalGroup(
            jPanelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajosLayout.createSequentialGroup()
                .addComponent(jPanelTop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trabajos", jPanelTrabajos);

        jPanelTop.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop.setToolTipText("");

        listaFincas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas.setText("Empleados");

        jLabelGestionar1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar1.setText("Volver");

        jCheckBoxTract.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxTract.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTract.setSelected(true);
        jCheckBoxTract.setText("Tractoristas");
        jCheckBoxTract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTractActionPerformed(evt);
            }
        });

        jCheckBoxEmp1.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxEmp1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxEmp1.setSelected(true);
        jCheckBoxEmp1.setText("Empleados");
        jCheckBoxEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEmp1ActionPerformed(evt);
            }
        });

        jCheckBoxEnc.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxEnc.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxEnc.setSelected(true);
        jCheckBoxEnc.setText("Encargados");
        jCheckBoxEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEncActionPerformed(evt);
            }
        });

        jCheckBoxFin.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxFin.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxFin.setText("Contratos finalizados");
        jCheckBoxFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar1)
                .addGap(184, 184, 184)
                .addComponent(listaFincas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEmp1)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxTract)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxEnc)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxFin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTract)
                    .addComponent(jCheckBoxEnc)
                    .addComponent(jCheckBoxFin)
                    .addComponent(jCheckBoxEmp1))
                .addGap(10, 10, 10))
        );

        jPanelBot.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot.setToolTipText("");

        jLabelCambiar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCambiar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_gest.png"))); // NOI18N
        jLabelCambiar.setText("Cambiar puesto");

        jLabelAdd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd.setText("Añadir");

        jLabelMod.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod.setText("Modificar");

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_info.png"))); // NOI18N
        jLabelInfo.setText("Informacion");

        jLabelEliminar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
        jPanelBot.setLayout(jPanelBotLayout);
        jPanelBotLayout.setHorizontalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabelCambiar)
                .addGap(64, 64, 64)
                .addComponent(jLabelAdd)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod)
                .addGap(64, 64, 64)
                .addComponent(jLabelInfo)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelBotLayout.setVerticalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCambiar)
                    .addComponent(jLabelAdd)
                    .addComponent(jLabelMod)
                    .addComponent(jLabelInfo)
                    .addComponent(jLabelEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellidos", "Teléfono", "F. Fin", "F.Inicio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelTrabajadoresLayout = new javax.swing.GroupLayout(jPanelTrabajadores);
        jPanelTrabajadores.setLayout(jPanelTrabajadoresLayout);
        jPanelTrabajadoresLayout.setHorizontalGroup(
            jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelTrabajadoresLayout.setVerticalGroup(
            jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajadoresLayout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trabajadores", jPanelTrabajadores);

        jPanelTop3.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop3.setToolTipText("");
        jPanelTop3.setPreferredSize(new java.awt.Dimension(954, 100));

        listaFincas3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas3.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas3.setText("Cuadrillas");

        jLabelGestionar5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar5.setText("Volver");

        javax.swing.GroupLayout jPanelTop3Layout = new javax.swing.GroupLayout(jPanelTop3);
        jPanelTop3.setLayout(jPanelTop3Layout);
        jPanelTop3Layout.setHorizontalGroup(
            jPanelTop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar5)
                .addGap(184, 184, 184)
                .addComponent(listaFincas3)
                .addContainerGap(486, Short.MAX_VALUE))
        );
        jPanelTop3Layout.setVerticalGroup(
            jPanelTop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelBot3.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot3.setToolTipText("");

        jLabelGestionar6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_gest.png"))); // NOI18N
        jLabelGestionar6.setText("Nuevo trabajo");

        jLabelAdd3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd3.setText("Añadir");

        jLabelMod3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod3.setText("Modificar");

        jLabelInfo2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelInfo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_info.png"))); // NOI18N
        jLabelInfo2.setText("Informacion");

        jLabelEliminar3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar3.setText("Eliminar");

        javax.swing.GroupLayout jPanelBot3Layout = new javax.swing.GroupLayout(jPanelBot3);
        jPanelBot3.setLayout(jPanelBot3Layout);
        jPanelBot3Layout.setHorizontalGroup(
            jPanelBot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabelGestionar6)
                .addGap(64, 64, 64)
                .addComponent(jLabelAdd3)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod3)
                .addGap(64, 64, 64)
                .addComponent(jLabelInfo2)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBot3Layout.setVerticalGroup(
            jPanelBot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGestionar6)
                    .addComponent(jLabelAdd3)
                    .addComponent(jLabelMod3)
                    .addComponent(jLabelInfo2)
                    .addComponent(jLabelEliminar3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Encargado", "último trab.", "F. Creación"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanelCuadrillas1Layout = new javax.swing.GroupLayout(jPanelCuadrillas1);
        jPanelCuadrillas1.setLayout(jPanelCuadrillas1Layout);
        jPanelCuadrillas1Layout.setHorizontalGroup(
            jPanelCuadrillas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop3, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
            .addComponent(jPanelBot3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        jPanelCuadrillas1Layout.setVerticalGroup(
            jPanelCuadrillas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCuadrillas1Layout.createSequentialGroup()
                .addComponent(jPanelTop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cuadrillas", jPanelCuadrillas1);

        jPanelTop4.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop4.setToolTipText("");
        jPanelTop4.setPreferredSize(new java.awt.Dimension(954, 100));

        listaFincas4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas4.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas4.setText("Trabajos");

        jLabelGestionar7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar7.setText("Volver");

        javax.swing.GroupLayout jPanelTop4Layout = new javax.swing.GroupLayout(jPanelTop4);
        jPanelTop4.setLayout(jPanelTop4Layout);
        jPanelTop4Layout.setHorizontalGroup(
            jPanelTop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar7)
                .addGap(235, 235, 235)
                .addComponent(listaFincas4)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanelTop4Layout.setVerticalGroup(
            jPanelTop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelBot4.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot4.setToolTipText("");

        jLabelAdd4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd4.setText("Añadir");

        jLabelMod4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod4.setText("Modificar");

        jLabelEliminar4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar4.setText("Eliminar");

        javax.swing.GroupLayout jPanelBot4Layout = new javax.swing.GroupLayout(jPanelBot4);
        jPanelBot4.setLayout(jPanelBot4Layout);
        jPanelBot4Layout.setHorizontalGroup(
            jPanelBot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot4Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabelAdd4)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod4)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar4)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanelBot4Layout.setVerticalGroup(
            jPanelBot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdd4)
                    .addComponent(jLabelMod4)
                    .addComponent(jLabelEliminar4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cuadrilla", "Fecha", "Horas", "Tipo", "Explotacion", "Encargado"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanelTrabajos1Layout = new javax.swing.GroupLayout(jPanelTrabajos1);
        jPanelTrabajos1.setLayout(jPanelTrabajos1Layout);
        jPanelTrabajos1Layout.setHorizontalGroup(
            jPanelTrabajos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop4, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
            .addComponent(jPanelBot4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
        );
        jPanelTrabajos1Layout.setVerticalGroup(
            jPanelTrabajos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajos1Layout.createSequentialGroup()
                .addComponent(jPanelTop4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Trabajos", jPanelTrabajos1);

        jPanelTop5.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop5.setToolTipText("");

        listaFincas5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas5.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas5.setText("Empleados");

        jLabelGestionar8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar8.setText("Volver");

        jCheckBoxTract1.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxTract1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTract1.setSelected(true);
        jCheckBoxTract1.setText("Tractoristas");
        jCheckBoxTract1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTract1ActionPerformed(evt);
            }
        });

        jCheckBoxEmp2.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxEmp2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxEmp2.setSelected(true);
        jCheckBoxEmp2.setText("Empleados");
        jCheckBoxEmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEmp2ActionPerformed(evt);
            }
        });

        jCheckBoxEnc1.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxEnc1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxEnc1.setSelected(true);
        jCheckBoxEnc1.setText("Encargados");
        jCheckBoxEnc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEnc1ActionPerformed(evt);
            }
        });

        jCheckBoxFin1.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxFin1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxFin1.setText("Contratos finalizados");
        jCheckBoxFin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTop5Layout = new javax.swing.GroupLayout(jPanelTop5);
        jPanelTop5.setLayout(jPanelTop5Layout);
        jPanelTop5Layout.setHorizontalGroup(
            jPanelTop5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar8)
                .addGap(184, 184, 184)
                .addComponent(listaFincas5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEmp2)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxTract1)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxEnc1)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxFin1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTop5Layout.setVerticalGroup(
            jPanelTop5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTop5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTop5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTop5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTract1)
                    .addComponent(jCheckBoxEnc1)
                    .addComponent(jCheckBoxFin1)
                    .addComponent(jCheckBoxEmp2))
                .addGap(10, 10, 10))
        );

        jPanelBot5.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot5.setToolTipText("");

        jLabelCambiar1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCambiar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCambiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_gest.png"))); // NOI18N
        jLabelCambiar1.setText("Cambiar puesto");

        jLabelAdd5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd5.setText("Añadir");

        jLabelMod5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod5.setText("Modificar");

        jLabelInfo3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelInfo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_info.png"))); // NOI18N
        jLabelInfo3.setText("Informacion");

        jLabelEliminar5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar5.setText("Eliminar");

        javax.swing.GroupLayout jPanelBot5Layout = new javax.swing.GroupLayout(jPanelBot5);
        jPanelBot5.setLayout(jPanelBot5Layout);
        jPanelBot5Layout.setHorizontalGroup(
            jPanelBot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabelCambiar1)
                .addGap(64, 64, 64)
                .addComponent(jLabelAdd5)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod5)
                .addGap(64, 64, 64)
                .addComponent(jLabelInfo3)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar5)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelBot5Layout.setVerticalGroup(
            jPanelBot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCambiar1)
                    .addComponent(jLabelAdd5)
                    .addComponent(jLabelMod5)
                    .addComponent(jLabelInfo3)
                    .addComponent(jLabelEliminar5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellidos", "Teléfono", "F. Fin", "F.Inicio"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout jPanelTrabajadores1Layout = new javax.swing.GroupLayout(jPanelTrabajadores1);
        jPanelTrabajadores1.setLayout(jPanelTrabajadores1Layout);
        jPanelTrabajadores1Layout.setHorizontalGroup(
            jPanelTrabajadores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBot5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );
        jPanelTrabajadores1Layout.setVerticalGroup(
            jPanelTrabajadores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajadores1Layout.createSequentialGroup()
                .addComponent(jPanelTop5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Trabajadores", jPanelTrabajadores1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxTractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTractActionPerformed

    private void jCheckBoxEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEmp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEmp1ActionPerformed

    private void jCheckBoxEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEncActionPerformed

    private void jCheckBoxFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFinActionPerformed

    private void jCheckBoxTract1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTract1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTract1ActionPerformed

    private void jCheckBoxEmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEmp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEmp2ActionPerformed

    private void jCheckBoxEnc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEnc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEnc1ActionPerformed

    private void jCheckBoxFin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFin1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxEmp1;
    private javax.swing.JCheckBox jCheckBoxEmp2;
    private javax.swing.JCheckBox jCheckBoxEnc;
    private javax.swing.JCheckBox jCheckBoxEnc1;
    private javax.swing.JCheckBox jCheckBoxFin;
    private javax.swing.JCheckBox jCheckBoxFin1;
    private javax.swing.JCheckBox jCheckBoxTract;
    private javax.swing.JCheckBox jCheckBoxTract1;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelAdd1;
    private javax.swing.JLabel jLabelAdd2;
    private javax.swing.JLabel jLabelAdd3;
    private javax.swing.JLabel jLabelAdd4;
    private javax.swing.JLabel jLabelAdd5;
    private javax.swing.JLabel jLabelCambiar;
    private javax.swing.JLabel jLabelCambiar1;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelEliminar1;
    private javax.swing.JLabel jLabelEliminar2;
    private javax.swing.JLabel jLabelEliminar3;
    private javax.swing.JLabel jLabelEliminar4;
    private javax.swing.JLabel jLabelEliminar5;
    private javax.swing.JLabel jLabelGestionar1;
    private javax.swing.JLabel jLabelGestionar2;
    private javax.swing.JLabel jLabelGestionar3;
    private javax.swing.JLabel jLabelGestionar4;
    private javax.swing.JLabel jLabelGestionar5;
    private javax.swing.JLabel jLabelGestionar6;
    private javax.swing.JLabel jLabelGestionar7;
    private javax.swing.JLabel jLabelGestionar8;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInfo1;
    private javax.swing.JLabel jLabelInfo2;
    private javax.swing.JLabel jLabelInfo3;
    private javax.swing.JLabel jLabelMod;
    private javax.swing.JLabel jLabelMod1;
    private javax.swing.JLabel jLabelMod2;
    private javax.swing.JLabel jLabelMod3;
    private javax.swing.JLabel jLabelMod4;
    private javax.swing.JLabel jLabelMod5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelBot1;
    private javax.swing.JPanel jPanelBot2;
    private javax.swing.JPanel jPanelBot3;
    private javax.swing.JPanel jPanelBot4;
    private javax.swing.JPanel jPanelBot5;
    private javax.swing.JPanel jPanelCuadrillas;
    private javax.swing.JPanel jPanelCuadrillas1;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTop1;
    private javax.swing.JPanel jPanelTop2;
    private javax.swing.JPanel jPanelTop3;
    private javax.swing.JPanel jPanelTop4;
    private javax.swing.JPanel jPanelTop5;
    private javax.swing.JPanel jPanelTrabajadores;
    private javax.swing.JPanel jPanelTrabajadores1;
    private javax.swing.JPanel jPanelTrabajos;
    private javax.swing.JPanel jPanelTrabajos1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JLabel listaFincas;
    private javax.swing.JLabel listaFincas1;
    private javax.swing.JLabel listaFincas2;
    private javax.swing.JLabel listaFincas3;
    private javax.swing.JLabel listaFincas4;
    private javax.swing.JLabel listaFincas5;
    // End of variables declaration//GEN-END:variables
}
