/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1daw.vistas;

import java.awt.Toolkit;

/**
 *
 * @author Jaime-torre
 */
public class JFGasto extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public JFGasto() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/proyecto1daw/img/icono_logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jLabelFinca = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        jLabelIngresos = new javax.swing.JLabel();
        jLabelCantidadIngresos = new javax.swing.JLabel();
        jLabelGast = new javax.swing.JLabel();
        jLabelCantidadGastos = new javax.swing.JLabel();
        jLabelBenef = new javax.swing.JLabel();
        jLabelCantidadBeneficio = new javax.swing.JLabel();
        jPanelBot = new javax.swing.JPanel();
        botonAddGasto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jLabelTituloGastos = new javax.swing.JLabel();
        botonModGasto = new javax.swing.JButton();
        botonEliminarGasto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPeriodos = new javax.swing.JList<>();
        jComboTipoPer = new javax.swing.JComboBox<>();
        jComboAnio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plantaciones y Ventas");
        setBackground(new java.awt.Color(174, 207, 182));

        jPanelTop.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop.setToolTipText("");

        jLabelFinca.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelFinca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFinca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFinca.setText("IdFinca");

        botonVolver.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.setBorderPainted(false);
        botonVolver.setContentAreaFilled(false);

        jLabelIngresos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngresos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelIngresos.setText("Ingresos:");

        jLabelCantidadIngresos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadIngresos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCantidadIngresos.setText("0.0€");

        jLabelGast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGast.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGast.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelGast.setText("Gastos:");

        jLabelCantidadGastos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadGastos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadGastos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCantidadGastos.setText("0.0€");

        jLabelBenef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBenef.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBenef.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBenef.setText("Beneficio");

        jLabelCantidadBeneficio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadBeneficio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadBeneficio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCantidadBeneficio.setText("0.0€");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(botonVolver)
                        .addGap(254, 254, 254)
                        .addComponent(jLabelFinca))
                    .addGroup(jPanelTopLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabelIngresos)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCantidadIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabelGast)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCantidadGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabelBenef)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCantidadBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFinca)
                    .addComponent(botonVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBenef)
                        .addComponent(jLabelCantidadBeneficio))
                    .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGast)
                        .addComponent(jLabelCantidadGastos)
                        .addComponent(jLabelCantidadIngresos))
                    .addComponent(jLabelIngresos))
                .addContainerGap())
        );

        jPanelBot.setBackground(new java.awt.Color(119, 182, 134));

        botonAddGasto.setForeground(new java.awt.Color(255, 255, 255));
        botonAddGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        botonAddGasto.setText("Añadir Gasto");
        botonAddGasto.setBorderPainted(false);
        botonAddGasto.setContentAreaFilled(false);
        botonAddGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddGastoActionPerformed(evt);
            }
        });

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "KG", "€/Kg", "Color", "TOTAL €€€", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVentas.setSelectionBackground(new java.awt.Color(182, 223, 178));
        jScrollPane2.setViewportView(jTableVentas);

        jLabelTituloGastos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTituloGastos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloGastos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTituloGastos.setText("Gastos");

        botonModGasto.setForeground(new java.awt.Color(255, 255, 255));
        botonModGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        botonModGasto.setText("Modificar");
        botonModGasto.setBorderPainted(false);
        botonModGasto.setContentAreaFilled(false);

        botonEliminarGasto.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        botonEliminarGasto.setText("Eliminar");
        botonEliminarGasto.setBorderPainted(false);
        botonEliminarGasto.setContentAreaFilled(false);

        jListPeriodos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListPeriodos);

        jComboTipoPer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
        jPanelBot.setLayout(jPanelBotLayout);
        jPanelBotLayout.setHorizontalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jComboTipoPer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jComboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloGastos)
                .addGap(283, 283, 283))
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(botonAddGasto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonModGasto)
                        .addGap(93, 93, 93)
                        .addComponent(botonEliminarGasto)
                        .addGap(84, 84, 84)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBotLayout.setVerticalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloGastos)
                    .addComponent(jComboTipoPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonModGasto)
                            .addComponent(botonEliminarGasto)
                            .addComponent(botonAddGasto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAddGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAddGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAddGasto;
    public javax.swing.JButton botonEliminarGasto;
    public javax.swing.JButton botonModGasto;
    public javax.swing.JButton botonVolver;
    public javax.swing.JComboBox<String> jComboAnio;
    public javax.swing.JComboBox<String> jComboTipoPer;
    private javax.swing.JLabel jLabelBenef;
    public javax.swing.JLabel jLabelCantidadBeneficio;
    public javax.swing.JLabel jLabelCantidadGastos;
    public javax.swing.JLabel jLabelCantidadIngresos;
    public javax.swing.JLabel jLabelFinca;
    private javax.swing.JLabel jLabelGast;
    private javax.swing.JLabel jLabelIngresos;
    public javax.swing.JLabel jLabelTituloGastos;
    public javax.swing.JList<String> jListPeriodos;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableVentas;
    // End of variables declaration//GEN-END:variables
}
