/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1daw.vistas;

import java.awt.Toolkit;

/**
 *
 * @author Jaime-torre
 */
public class JFPlantacion extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public JFPlantacion() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/proyecto1daw/img/icono_logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jLabelExplotacion = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonAddVenta = new javax.swing.JButton();
        botonModPlant = new javax.swing.JButton();
        botonEliminarPlant = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlantaciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jLabelCantidadIngresos = new javax.swing.JLabel();
        jLabelVentas = new javax.swing.JLabel();
        botonAddPlant = new javax.swing.JButton();
        botonModVenta = new javax.swing.JButton();
        botonEliminarVent = new javax.swing.JButton();
        campoFIn = new javax.swing.JTextField();
        campoFFin = new javax.swing.JTextField();
        jLabelFPlant = new javax.swing.JLabel();
        jLabelFFin = new javax.swing.JLabel();
        campoFVentaInicio = new javax.swing.JTextField();
        jLabelFVentaIni = new javax.swing.JLabel();
        botonBuscarPlant = new javax.swing.JButton();
        jLabelPlantacion = new javax.swing.JLabel();
        jLabelIngresos = new javax.swing.JLabel();
        botonBuscarVenta = new javax.swing.JButton();
        jLabelQuinAnt = new javax.swing.JLabel();
        jLabelCantidadQAnt = new javax.swing.JLabel();
        jLabelQuinActual = new javax.swing.JLabel();
        jLabelCantidadQActual = new javax.swing.JLabel();
        jLabelFVentaFin = new javax.swing.JLabel();
        campoFVentaFin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plantaciones y Ventas");
        setBackground(new java.awt.Color(174, 207, 182));

        jPanelTop.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop.setToolTipText("");

        jLabelExplotacion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelExplotacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExplotacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelExplotacion.setText("IdExp");

        botonVolver.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.setBorderPainted(false);
        botonVolver.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(botonVolver)
                .addGap(254, 254, 254)
                .addComponent(jLabelExplotacion)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelExplotacion)
                    .addComponent(botonVolver))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(119, 182, 134));

        botonAddVenta.setForeground(new java.awt.Color(255, 255, 255));
        botonAddVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        botonAddVenta.setText("Añadir Venta");
        botonAddVenta.setBorderPainted(false);
        botonAddVenta.setContentAreaFilled(false);
        botonAddVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddVentaActionPerformed(evt);
            }
        });

        botonModPlant.setForeground(new java.awt.Color(255, 255, 255));
        botonModPlant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        botonModPlant.setText("Modificar");
        botonModPlant.setBorderPainted(false);
        botonModPlant.setContentAreaFilled(false);

        botonEliminarPlant.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarPlant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        botonEliminarPlant.setText("Eliminar");
        botonEliminarPlant.setBorderPainted(false);
        botonEliminarPlant.setContentAreaFilled(false);

        jTablePlantaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Variedad", "Fecha Plant", "Fecha Fn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePlantaciones.setSelectionBackground(new java.awt.Color(182, 223, 178));
        jScrollPane1.setViewportView(jTablePlantaciones);

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "KG", "€/Kg", "Color", "TOTAL €€€", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVentas.setSelectionBackground(new java.awt.Color(182, 223, 178));
        jScrollPane2.setViewportView(jTableVentas);

        jLabelCantidadIngresos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadIngresos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCantidadIngresos.setText("0.0€");

        jLabelVentas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVentas.setText("Ventas");

        botonAddPlant.setForeground(new java.awt.Color(255, 255, 255));
        botonAddPlant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        botonAddPlant.setText("Añadir Plantacion");
        botonAddPlant.setBorderPainted(false);
        botonAddPlant.setContentAreaFilled(false);
        botonAddPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddPlantActionPerformed(evt);
            }
        });

        botonModVenta.setForeground(new java.awt.Color(255, 255, 255));
        botonModVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        botonModVenta.setText("Modificar");
        botonModVenta.setBorderPainted(false);
        botonModVenta.setContentAreaFilled(false);

        botonEliminarVent.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarVent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        botonEliminarVent.setText("Eliminar");
        botonEliminarVent.setBorderPainted(false);
        botonEliminarVent.setContentAreaFilled(false);

        jLabelFPlant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFPlant.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFPlant.setText("Fecha de plantación");

        jLabelFFin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFFin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFFin.setText("Fecha de fin");

        jLabelFVentaIni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFVentaIni.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFVentaIni.setText("Fecha inicio de ventas");

        botonBuscarPlant.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarPlant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_buscar.png"))); // NOI18N
        botonBuscarPlant.setText("Buscar");
        botonBuscarPlant.setBorderPainted(false);
        botonBuscarPlant.setContentAreaFilled(false);

        jLabelPlantacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPlantacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlantacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPlantacion.setText("Plantaciones");

        jLabelIngresos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngresos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelIngresos.setText("Ingresos plantación:");

        botonBuscarVenta.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_buscar.png"))); // NOI18N
        botonBuscarVenta.setText("Buscar");
        botonBuscarVenta.setBorderPainted(false);
        botonBuscarVenta.setContentAreaFilled(false);

        jLabelQuinAnt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelQuinAnt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuinAnt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelQuinAnt.setText("Quincena anterior:");

        jLabelCantidadQAnt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadQAnt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadQAnt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCantidadQAnt.setText("0.0€");

        jLabelQuinActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelQuinActual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuinActual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelQuinActual.setText("Quincena actual:");

        jLabelCantidadQActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadQActual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadQActual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCantidadQActual.setText("0.0€");

        jLabelFVentaFin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFVentaFin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFVentaFin.setText("Fecha fin de ventas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabelPlantacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelVentas)
                .addGap(149, 149, 149))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAddPlant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModPlant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarPlant)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(botonBuscarVenta)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFFin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoFIn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFFin)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelQuinActual)
                                .addGap(38, 38, 38)
                                .addComponent(jLabelCantidadQActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelIngresos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCantidadIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelQuinAnt)
                                .addGap(24, 24, 24)
                                .addComponent(jLabelCantidadQAnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(campoFVentaInicio)
                            .addComponent(campoFVentaFin)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFVentaIni)
                                    .addComponent(jLabelFVentaFin))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelFPlant))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(botonBuscarPlant)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAddVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarVent))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVentas)
                    .addComponent(jLabelPlantacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonModVenta)
                                .addComponent(botonEliminarVent))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonAddPlant)
                                .addComponent(botonAddVenta)
                                .addComponent(botonModPlant)
                                .addComponent(botonEliminarPlant))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelFPlant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarPlant)
                        .addGap(13, 13, 13)
                        .addComponent(jLabelFVentaIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFVentaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelFVentaFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFVentaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBuscarVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIngresos)
                            .addComponent(jLabelCantidadIngresos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuinAnt)
                            .addComponent(jLabelCantidadQAnt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuinActual)
                            .addComponent(jLabelCantidadQActual))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAddVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAddVentaActionPerformed

    private void botonAddPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddPlantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAddPlantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPlantacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPlantacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPlantacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPlantacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAddPlant;
    public javax.swing.JButton botonAddVenta;
    public javax.swing.JButton botonBuscarPlant;
    public javax.swing.JButton botonBuscarVenta;
    public javax.swing.JButton botonEliminarPlant;
    public javax.swing.JButton botonEliminarVent;
    public javax.swing.JButton botonModPlant;
    public javax.swing.JButton botonModVenta;
    public javax.swing.JButton botonVolver;
    public javax.swing.JTextField campoFFin;
    public javax.swing.JTextField campoFIn;
    public javax.swing.JTextField campoFVentaFin;
    public javax.swing.JTextField campoFVentaInicio;
    public javax.swing.JLabel jLabelCantidadIngresos;
    public javax.swing.JLabel jLabelCantidadQActual;
    public javax.swing.JLabel jLabelCantidadQAnt;
    public javax.swing.JLabel jLabelExplotacion;
    private javax.swing.JLabel jLabelFFin;
    private javax.swing.JLabel jLabelFPlant;
    private javax.swing.JLabel jLabelFVentaFin;
    private javax.swing.JLabel jLabelFVentaIni;
    private javax.swing.JLabel jLabelIngresos;
    public javax.swing.JLabel jLabelPlantacion;
    private javax.swing.JLabel jLabelQuinActual;
    private javax.swing.JLabel jLabelQuinAnt;
    public javax.swing.JLabel jLabelVentas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTablePlantaciones;
    public javax.swing.JTable jTableVentas;
    // End of variables declaration//GEN-END:variables
}
