/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1daw.vistas;

/**
 *
 * @author Jaime-torre
 */
public class TrabajadoresCuadrillas extends javax.swing.JPanel {

    /**
     * Creates new form TrabajadoresCuadrillas
     */
    public TrabajadoresCuadrillas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTrabajadores = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        listaFincas = new javax.swing.JLabel();
        jLabelGestionar1 = new javax.swing.JLabel();
        jCheckBoxTract = new javax.swing.JCheckBox();
        jCheckBoxEmp1 = new javax.swing.JCheckBox();
        jCheckBoxEnc = new javax.swing.JCheckBox();
        jCheckBoxFin = new javax.swing.JCheckBox();
        jPanelBot = new javax.swing.JPanel();
        jLabelGestionar = new javax.swing.JLabel();
        jLabelAdd = new javax.swing.JLabel();
        jLabelMod = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelCuadrillas = new javax.swing.JPanel();
        jPanelTop1 = new javax.swing.JPanel();
        listaFincas1 = new javax.swing.JLabel();
        jLabelGestionar2 = new javax.swing.JLabel();
        jPanelBot1 = new javax.swing.JPanel();
        jLabelGestionar3 = new javax.swing.JLabel();
        jLabelAdd1 = new javax.swing.JLabel();
        jLabelMod1 = new javax.swing.JLabel();
        jLabelInfo1 = new javax.swing.JLabel();
        jLabelEliminar1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelTrabajos = new javax.swing.JPanel();
        jPanelTop2 = new javax.swing.JPanel();
        listaFincas2 = new javax.swing.JLabel();
        jLabelGestionar4 = new javax.swing.JLabel();
        jPanelBot2 = new javax.swing.JPanel();
        jLabelAdd2 = new javax.swing.JLabel();
        jLabelMod2 = new javax.swing.JLabel();
        jLabelEliminar2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jPanelTop.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop.setToolTipText("");

        listaFincas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas.setText("Empleados");

        jLabelGestionar1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar1.setText("Volver");

        jCheckBoxTract.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxTract.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTract.setText("Tractoristas");
        jCheckBoxTract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTractActionPerformed(evt);
            }
        });

        jCheckBoxEmp1.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxEmp1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxEmp1.setText("Empleados");
        jCheckBoxEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEmp1ActionPerformed(evt);
            }
        });

        jCheckBoxEnc.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxEnc.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxEnc.setText("Encargados");
        jCheckBoxEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEncActionPerformed(evt);
            }
        });

        jCheckBoxFin.setBackground(new java.awt.Color(119, 182, 134));
        jCheckBoxFin.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxFin.setText("Contratos finalizados");
        jCheckBoxFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar1)
                .addGap(184, 184, 184)
                .addComponent(listaFincas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEmp1)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxTract)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxEnc)
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxFin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTract)
                    .addComponent(jCheckBoxEnc)
                    .addComponent(jCheckBoxFin)
                    .addComponent(jCheckBoxEmp1))
                .addGap(10, 10, 10))
        );

        jPanelBot.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot.setToolTipText("");

        jLabelGestionar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_gest.png"))); // NOI18N
        jLabelGestionar.setText("Extender contrato");

        jLabelAdd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd.setText("Añadir");

        jLabelMod.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod.setText("Modificar");

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_info.png"))); // NOI18N
        jLabelInfo.setText("Informacion");

        jLabelEliminar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
        jPanelBot.setLayout(jPanelBotLayout);
        jPanelBotLayout.setHorizontalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabelGestionar)
                .addGap(64, 64, 64)
                .addComponent(jLabelAdd)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod)
                .addGap(64, 64, 64)
                .addComponent(jLabelInfo)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelBotLayout.setVerticalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGestionar)
                    .addComponent(jLabelAdd)
                    .addComponent(jLabelMod)
                    .addComponent(jLabelInfo)
                    .addComponent(jLabelEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelTrabajadoresLayout = new javax.swing.GroupLayout(jPanelTrabajadores);
        jPanelTrabajadores.setLayout(jPanelTrabajadoresLayout);
        jPanelTrabajadoresLayout.setHorizontalGroup(
            jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelTrabajadoresLayout.setVerticalGroup(
            jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajadoresLayout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trabajadores", jPanelTrabajadores);

        jPanelTop1.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop1.setToolTipText("");
        jPanelTop1.setPreferredSize(new java.awt.Dimension(954, 100));

        listaFincas1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas1.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas1.setText("Cuadrillas");

        jLabelGestionar2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar2.setText("Volver");

        javax.swing.GroupLayout jPanelTop1Layout = new javax.swing.GroupLayout(jPanelTop1);
        jPanelTop1.setLayout(jPanelTop1Layout);
        jPanelTop1Layout.setHorizontalGroup(
            jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar2)
                .addGap(184, 184, 184)
                .addComponent(listaFincas1)
                .addContainerGap(486, Short.MAX_VALUE))
        );
        jPanelTop1Layout.setVerticalGroup(
            jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelBot1.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot1.setToolTipText("");

        jLabelGestionar3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_gest.png"))); // NOI18N
        jLabelGestionar3.setText("Nuevo trabajo");

        jLabelAdd1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd1.setText("Añadir");

        jLabelMod1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod1.setText("Modificar");

        jLabelInfo1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelInfo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_info.png"))); // NOI18N
        jLabelInfo1.setText("Informacion");

        jLabelEliminar1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar1.setText("Eliminar");

        javax.swing.GroupLayout jPanelBot1Layout = new javax.swing.GroupLayout(jPanelBot1);
        jPanelBot1.setLayout(jPanelBot1Layout);
        jPanelBot1Layout.setHorizontalGroup(
            jPanelBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabelGestionar3)
                .addGap(64, 64, 64)
                .addComponent(jLabelAdd1)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod1)
                .addGap(64, 64, 64)
                .addComponent(jLabelInfo1)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBot1Layout.setVerticalGroup(
            jPanelBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGestionar3)
                    .addComponent(jLabelAdd1)
                    .addComponent(jLabelMod1)
                    .addComponent(jLabelInfo1)
                    .addComponent(jLabelEliminar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelCuadrillasLayout = new javax.swing.GroupLayout(jPanelCuadrillas);
        jPanelCuadrillas.setLayout(jPanelCuadrillasLayout);
        jPanelCuadrillasLayout.setHorizontalGroup(
            jPanelCuadrillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop1, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
            .addComponent(jPanelBot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanelCuadrillasLayout.setVerticalGroup(
            jPanelCuadrillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCuadrillasLayout.createSequentialGroup()
                .addComponent(jPanelTop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuadrillas", jPanelCuadrillas);

        jPanelTop2.setBackground(new java.awt.Color(119, 182, 134));
        jPanelTop2.setToolTipText("");
        jPanelTop2.setPreferredSize(new java.awt.Dimension(954, 100));

        listaFincas2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        listaFincas2.setForeground(new java.awt.Color(255, 255, 255));
        listaFincas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listaFincas2.setText("Trabajos");

        jLabelGestionar4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelGestionar4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestionar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_back.png"))); // NOI18N
        jLabelGestionar4.setText("Volver");

        javax.swing.GroupLayout jPanelTop2Layout = new javax.swing.GroupLayout(jPanelTop2);
        jPanelTop2.setLayout(jPanelTop2Layout);
        jPanelTop2Layout.setHorizontalGroup(
            jPanelTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelGestionar4)
                .addGap(235, 235, 235)
                .addComponent(listaFincas2)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanelTop2Layout.setVerticalGroup(
            jPanelTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaFincas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGestionar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelBot2.setBackground(new java.awt.Color(119, 182, 134));
        jPanelBot2.setToolTipText("");

        jLabelAdd2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelAdd2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_add.png"))); // NOI18N
        jLabelAdd2.setText("Añadir");

        jLabelMod2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMod2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMod2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_edit.png"))); // NOI18N
        jLabelMod2.setText("Modificar");

        jLabelEliminar2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1daw/img/ico_borrar.png"))); // NOI18N
        jLabelEliminar2.setText("Eliminar");

        javax.swing.GroupLayout jPanelBot2Layout = new javax.swing.GroupLayout(jPanelBot2);
        jPanelBot2.setLayout(jPanelBot2Layout);
        jPanelBot2Layout.setHorizontalGroup(
            jPanelBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot2Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabelAdd2)
                .addGap(64, 64, 64)
                .addComponent(jLabelMod2)
                .addGap(64, 64, 64)
                .addComponent(jLabelEliminar2)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanelBot2Layout.setVerticalGroup(
            jPanelBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBot2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdd2)
                    .addComponent(jLabelMod2)
                    .addComponent(jLabelEliminar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanelTrabajosLayout = new javax.swing.GroupLayout(jPanelTrabajos);
        jPanelTrabajos.setLayout(jPanelTrabajosLayout);
        jPanelTrabajosLayout.setHorizontalGroup(
            jPanelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop2, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
            .addComponent(jPanelBot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanelTrabajosLayout.setVerticalGroup(
            jPanelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajosLayout.createSequentialGroup()
                .addComponent(jPanelTop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trabajos", jPanelTrabajos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxTractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTractActionPerformed

    private void jCheckBoxEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEmp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEmp1ActionPerformed

    private void jCheckBoxEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEncActionPerformed

    private void jCheckBoxFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxEmp1;
    private javax.swing.JCheckBox jCheckBoxEnc;
    private javax.swing.JCheckBox jCheckBoxFin;
    private javax.swing.JCheckBox jCheckBoxTract;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelAdd1;
    private javax.swing.JLabel jLabelAdd2;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelEliminar1;
    private javax.swing.JLabel jLabelEliminar2;
    private javax.swing.JLabel jLabelGestionar;
    private javax.swing.JLabel jLabelGestionar1;
    private javax.swing.JLabel jLabelGestionar2;
    private javax.swing.JLabel jLabelGestionar3;
    private javax.swing.JLabel jLabelGestionar4;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInfo1;
    private javax.swing.JLabel jLabelMod;
    private javax.swing.JLabel jLabelMod1;
    private javax.swing.JLabel jLabelMod2;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelBot1;
    private javax.swing.JPanel jPanelBot2;
    private javax.swing.JPanel jPanelCuadrillas;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTop1;
    private javax.swing.JPanel jPanelTop2;
    private javax.swing.JPanel jPanelTrabajadores;
    private javax.swing.JPanel jPanelTrabajos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel listaFincas;
    private javax.swing.JLabel listaFincas1;
    private javax.swing.JLabel listaFincas2;
    // End of variables declaration//GEN-END:variables
}
